AllCops:
  TargetRubyVersion: 2.6
  Exclude:
    - 'sig/*'

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Layout/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 20

Style/StderrPuts:
  Enabled: false

Style/Documentation:
  Enabled: false

Metrics/AbcSize:
  Max: 30

Security/YAMLLoad:
  Enabled: false
