# frozen_string_literal: true

module RDockerize
  module Commands
    class Dco < Base
      @user_temp: bool
      @show: bool
      @db: string
      @js: string
      @subservices: array[string]
      @volumes: string

      def initialize: (args: Hash[Symbol, bool]) -> void

      private

      def prepare_js: (string) -> void

      def prepare_db: (string) -> void

      def prepare_compose_version: (string) -> void

      def prepare_subservices: (string) -> void

      def prepare_volumes: -> string

      def prepare_text: -> string
    end
  end
end
