# frozen_string_literal: true

module RDockerize
  module Commands
    class Dco < Base
      attr_reader db: string
      attr_reader js: string
      attr_reader subservices: array[string]
      attr_reader volumes: string
      attr_reader show: bool

      def initialize: (args: Hash[Symbol, bool]) -> void

      private

      def prepare_js: (string) -> void

      def prepare_db: (string) -> void

      def prepare_compose_version: (string) -> void

      def prepare_subservices: (string) -> void

      def prepare_volumes: -> string

      def prepare_text: -> string
    end
  end
end
