# frozen_string_literal: true

module RDockerize
  module Commands
    class Save < Base

      private

      def save_template: -> untyped
      def docker_file?:(string, Symbol) -> (void | Exception)
    end
  end
end
